### Se om man är inloggad
POST http://localhost:3000/api/auth/sign-in/email
Origin: http://localhost:3000
Content-Type: application/json

{
  "email": "name@icloud.com",
  "password": "12345678"
}

###Hämta alla produkter
GET http://localhost:3000/api/products


###Hämta en specifik produkt  avänder samma som ovanför + produktNr
GET http://localhost:3000/api/products/115
